name: Sync Course and Grade Data

on:
  schedule:
    - cron: '0 */6 * * *'
  
  workflow_dispatch: 

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy sqlalchemy playwright requests python-dotenv openpyxl psycopg2-binary lxml

      - name: Install Playwright Chromium Browser
        run: playwright install chromium

      - name: Run scripts/upload_data.py
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: python scripts/upload_data.py
